version: "3"

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        image: bot
        container_name: bot
        restart: unless-stopped
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
